unit: "Sugar Land 2nd Ward"
meeting_cover_img: 'HoustonSouth' # Get alias from lookups/artlinks or from the arlinks web page
#meeting_type: "sacrament" # Auto-calculated. Uncomment for tests or overrides only. Acceptable values: sacrament, testimony, primary, easter, ward, christmas, stake, generalconference
officers:
  - "Presiding": "Bishop Cody Roskelley"
  #- "Presiding": "Elder Robert K. Ellis"
  #- "Presiding": "President Travis Bird"
  #- "Presiding": "President Mike Kennington"
  #- "Presiding": "President Ernie Carrasquillo"
  #- "Presiding": "Brother Jared Draney"
  #- "Presiding": "Brother Schuyler Robinson"
  #- "Conducting": "Bishop Cody Roskelley"
  - "Conducting": "Brother Jared Draney"
  #- "Conducting": "Brother Schuyler Robinson"
hymns:
  opening:
      number: 93
  sacrament:
      number: 173
  intermediate:
      number: 1096
  closing:
      number: 94
meeting_sacrament:
  title: "Sacrament Meeting"
  program:

    type: "speaker"
    name: "Mya Jones"

      #- type: "speaker"
      #  name: "Dora Powell"

      #- type: "music"
      #  title: "Amazing Grace" #Music number
      #  description: "Claire Drainey accompanied by Jared Draney" #Musicians

      # type: intermediate_hymn
    
      # type: "speaker"
      # name: "Clement Ozomah"
    
        
meeting_testimony:
  title: "Fast and Testimony Meeting"
  program:
      - type: custom
        title: "Bearing of Testimonies"
        description: ""

meeting_ward:
  title: "Ward Conference"
  program:

      - type: "speaker"
        name: "John Wick"

      - type: intermediate_hymn
    
      - type: "music"
        title: "Come ye saints... " #Music number
        description: "by Nan and Ann" #Musicians
    
      - type: "speaker"
        name: "Reuben Sams"

meeting_easter:
  title: "Easter Service"
  program:

      - type: "speaker"
        name: "Travis Bird"

      - type: "speaker"
        name: "Joey Powell"

      #- type: intermediate_hymn
    
      - type: "music"
        title: "Come ye saints... " #Music number
        description: "by Nan and Ann" #Musicians
    
      - type: "speaker"
        name: "David Hruska"

      - type: hymn
        hymn: closing

#meeting_christmas:
#  title: "Christmas Program"
#  program:
#      - type: custom
#        title: "Custom text"
#        description: "Custom text"

meeting_primary:
  title: "Primary Program"
  program:
      - type: custom
        title: "Primary Program"
        description: |
          Words and Music on the theme of Come, Follow Me
      - type: custom
        title: "Introductory Remarks"
        description: "President Ryman Tiu"

      - type: speaker
        name: "Dawnette Moore"

      - type: custom
        title: "Program of Words and music by Primary Children"
        description: "Directed by Tara Wightman, Accompanied by Dana Blackburn"

      - type: custom
        title: "Concluding Remarks"
        description: "Bishop Cody Roskelley"

meeting_stake:
  title: "Houston Texas South Stake Conference"
  program:
      #- type: custom
       # title: "Leadership Session, Saturday 4:00-5:30 pm"
       # description: |
       #   All members of Stake and Ward Councils and their presidencies, secretaries, and clerks are invited to attend.
       #   <br>This includes: Bishoprics; Elders quorum presidencies; Aaronic Priesthood quorum and Young Women class advisers; Relief Society, Young Women, Primary and Sunday School presidencies, and secretaries.
       #   <br>In-person at Lexington

      #- type: custom
       # title: "Adult Session, Saturday 7:00-8:45 pm"
       # description: "All adults. <br>In-person at Lexington"

      - type: custom
        title: "General Session, Sunday 10:00 am - 12:00 pm"
        description: "In-person at Lexington. Via Zoom at Sienna and Rosenberg buildings"

meeting_generalconference:
  title: "General Conference"
  program:
      - type: custom
        title: "Join General Conference"
        description:  |
         Saturday Morning Session - 11:00 am CDT
         <br>Saturday Afternoon Session - 3:00 pm CDT
         <br>Saturday Evening Session - 7:00 pm CDT
         <br>Sunday Morning Session - 11:00 am CDT
         <br>Sunday Afternoon Session - 3:00 pm CDT


      - type: url
        title: "Watch and listen online"
        url: "https://www.churchofjesuschrist.org/feature/general-conference?lang=eng"

announcements:
  #- "Fast Sunday for September will be observed on September 14"
  - "The sister missionaries have a new phone number: 346-901-8717"
  - "Volleyball Wednesdays - Come join us on Wednesdays at 9PM and have fun!!!"
  - "Send announcements to bvl2clerk@gmail.com"

posters: # Upload pictures to the GitHub docs/img/ folder. Avoid spaces in the picture filenames.
  - "./img/Stake%20Monthly%20Flyer.png"
  - "./img/Stake%20Monthly%20Flyer-2.png"
  #- "./img/Stake%20Save%20the%20Date.png"
  - "./posters/In-lawStrengtheningWorkshop.png"
  #- "./posters/FSY%20Wrap%20Up%20Fireside%20-%20Flyer%202025.JPG"

calendar:
  #temple_day: # Auto-calculated. Remove or comment this line to hide the next Ward temple day
  cleaning: # Auto-calculated. Remove or comment this line to hide the building cleaning schedule
    - title: "Stake Training for Ward Council Members and their presidencies"
      description: "November 9, 7 pm"
    - title: "Deseret Industries POD for donation of gently used clothing and household items"
      description: "November 17-24 at Lexington"   
    - title: "Stake Christmas Choir for concert on December 14"
      description: "Small group and solo performers are also sought."


links:
  - title: "See the entire building cleaning schedule"
    url: "./CleaningSchedule.html"
  - title: "See how to service soap dispensers"
    url: "https://drive.google.com/file/d/1OnMO0eZ_Z1fttxTsFR98yKebc1D8TfIx/view"
  - title: "See how to refill paper towel dispensers"
    url: "https://drive.google.com/file/d/19ApkyNN-MF4rDIM0hpOBLaLA5siyD8SY/view"
  - title: "See how to replace toilet paper rolls"
    url: "https://drive.google.com/file/d/1lt1iuTzIWgmp3sON7pSFb8uekS9wMQZ6/view?usp=sharing"
  - title: "Get started with Temple and Family History work"
    url: ./temple-and-family-history.html
  - title: "Sign up to feed the missionaries"
    url: ./temple-and-family-history.html
  - title: "Sign up to prepare a meal with Fort Bend Family Promise"
    url: https://www.signupgenius.com/go/10c0e4baca82ea7fb6-helping4#
  - title: "Help at secondmile.org"
    url: https://www.signupgenius.com/go/10c0e4baca82ea7fb6-helping4#

quote_of_the_month:
  #quote: "When so many around us are burdened with fear and uncertainty, I invite you to make room in your heart for those around you who may be struggling to see the light of the Savior and to feel His love. No gifts will mean as much as acts of pure love you offer to the lonely, the worn down and the weary. These are gifts that remind us and them of the true reason for the season: the gift of God’s Son, Jesus Christ, who was born to cast out all fear and bring everlasting light and joy to all who follow Him"
  #author: "Russell M. Nelson"
  quote: "Our ministry is a ministry of all the children of God on the face of the earth. We pray for all. We seek to serve all. And we invoke the blessings of the Lord Jesus Christ upon all who seek to serve Him, to do so in worthiness and commitment and optimism. We do not have the answers to all the world’s problems. They have not been revealed. But what we do know is that we are all children of heavenly parents, and that we are called to serve all of the children of God."
  author: "President Dallin H. Oaks"
